"""Actualizar SalesOrder: agregar customer_name, order_date, status, timestamps

Revision ID: d5aee9dbe461
Revises: fc02d24750ba
Create Date: 2025-10-21 05:17:00.440890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5aee9dbe461'
down_revision = 'fc02d24750ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Paso 1: Agregar columnas con nullable=True temporalmente
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('quote_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    
    # Paso 2: Actualizar registros existentes con valores por defecto
    op.execute("""
        UPDATE sales_order 
        SET customer_name = 'Cliente Legacy',
            order_date = date,
            status = 'pending',
            creation_date = CURRENT_TIMESTAMP,
            update_date = CURRENT_TIMESTAMP
        WHERE customer_name IS NULL
    """)
    
    # Paso 3: Hacer columnas NOT NULL y eliminar columna date
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('customer_name', nullable=False)
        batch_op.alter_column('order_date', nullable=False)
        batch_op.alter_column('status', nullable=False)
        batch_op.alter_column('creation_date', nullable=False)
        batch_op.alter_column('update_date', nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.alter_column('quote_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('update_date')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('status')
        batch_op.drop_column('order_date')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
